// Generated by https://quicktype.io

export interface Metadata {
    attributes:              Attribute[];
    description:             string;
    image:                   string;
    name:                    string;
    external_url:            string;
    seller_fee_basis_points: number;
    fee_recipient:           string;
  }
  
  export interface Attribute {
    trait_type:    string;
    value:         number | string;
    display_type?: string;
  }